### ISSUE TITLE
Add NDI input capability.

### ISSUE THREAD

**Issue by avsoundguy** [gbraad/NDI-Whiteboard#10] opened 2019-01-13 06:29 UTC
If NDI Whiteboard had the ability to load an NDI source onto the whiteboard drawing area then the transparent overlay within vMix (or other similar software) would exactly correlate and all the markups would be perfectly aligned since it would not be necessary to estimate the placement of the markups.

**Comment by gbraad** [comment] 2019-05-04 15:23
I might consider doing this... but have no idea if this will work well as it puts more load on the development/testing machine I use for this. I run the whiteboard on a ThinkPad 10 (Atom) tablet for use with streaming and use it with a standard Wacom stylus and the Wacom Slate pen with paper... so I actually do not really 'look' at the screen.

**Comment by gbraad** [comment] 2019-05-04 15:32
Actually, this is a duplicate of #2

**Closed as completed by gbraad** 2019-05-04 15:32 UTC
